### ISSUE TITLE
Tests results append (x2) when only run once.

### ISSUE THREAD

**Issue by jdeathe** [rylnd/shpec#116]
Since the release of 0.3.0 `(x2)` is being appended to some of my test messages despite them only running once.

shpec file: https://github.com/jdeathe/centos-ssh/blob/centos-7-develop/test/shpec/operation_shpec.sh

Reference: https://semaphoreci.com/jdeathe/centos-ssh/branches/centos-7-develop/builds/36

The output of my `make test`  using release `0.3.0` looks as follows

```
---> Functional test
jdeathe/centos-ssh:latest
  Basic SSH operations
    Runs an SSH container named ssh.pool-1.1.1 on port 2020.
    Generates a password that can be retrieved from the log.
      Displays the password in plain text.(x2)
    Allows the user to connect using SSH + private key authentication.
[password_test]      Requires a password for sudo commands.(x2)
  Basic SFTP operations
    Runs an SFTP container named sftp.pool-1.1.1 on port 2020.
    Allows the user to connect using SFTP + private key authentication.
      Allows the user to upload a file to their _data directory.(x2)
      Jails the user into a chroot directory.
  Customised SSH configuration
    Allows configuration of passwordless sudo.
      Displays the sudo settings in the logs output summary.(x2)
    Allows configuration of the username.
      Displays the user in the logs output summary.(x2)
    Allows configuration of an alternative public key.
      Displays the key's signature in the logs output summary.(x2)
      Allows multiple keys to be added as a base64 encoded string.
        Displays the key's signatures in the logs output summary.(x2)
    Allows configuration of the user's home directory where %u is replaced with the username in the path.
      Displays the user's home directory in the logs output summary.(x2)
    Allows configuration of the user's uid:gid.
      Displays the user's uid:gid in the logs output summary.(x2)
    Allows configuration of the user's shell.
      Displays the user's shell in the logs output summary.(x2)
    Allows configuration to enable the environment to be inherited.
[password_test]    Allows configuration of a plain text password.
      Will redact the user's password in the logs output summary.
[password_test]    Allows configuration of a hashed password.
      Will redact the user's password in the logs output summary.(x2)
    Allows preventing the startup of the sshd bootstrap.
    Allows preventing the startup of the sshd daemon.
  Customised SFTP configuration
    Allows configuration of the user's ChrootDirectory where %u is replaced with the username in the path.
      Displays the chroot path in the logs output summary.(x2)
      Configures the user with the /sbin/nologin shell.
        Displays the user's shell in the logs output summary.(x2)
      Allows the user to write to their HOME directory.
    Allows configuration of SFTP access to a volume mounted from another container.
37 examples, 0 failures
0m0.036s 0m0.041s
0m1.413s 0m0.864s
```

Reference: https://semaphoreci.com/jdeathe/centos-ssh/branches/centos-7-develop/builds/30

The output of `make test` using release `0.2.2` looked as follows:

```
---> Functional test
jdeathe/centos-ssh:latest
  Basic SSH operations
    Runs an SSH container named ssh.pool-1.1.1 on port 2020.
    Generates a password that can be retrieved from the log.
      Displays the password in plain text.
    Allows the user to connect using SSH + private key authentication.
[password_test]      Requires a password for sudo commands.
  Basic SFTP operations
    Runs an SFTP container named sftp.pool-1.1.1 on port 2020.
    Allows the user to connect using SFTP + private key authentication.
      Allows the user to upload a file to their _data directory.
      Jails the user into a chroot directory.
  Customised SSH configuration
    Allows configuration of passwordless sudo.
      Displays the sudo settings in the logs output summary.
    Allows configuration of the username.
      Displays the user in the logs output summary.
    Allows configuration of an alternative public key.
      Displays the key's signature in the logs output summary.
      Allows multiple keys to be added as a base64 encoded string.
        Displays the key's signatures in the logs output summary.
    Allows configuration of the user's home directory where %u is replaced with the username in the path.
      Displays the user's home directory in the logs output summary.
    Allows configuration of the user's uid:gid.
      Displays the user's uid:gid in the logs output summary.
    Allows configuration of the user's shell.
      Displays the user's shell in the logs output summary.
    Allows configuration to enable the environment to be inherited.
[password_test]    Allows configuration of a plain text password.
      Will redact the user's password in the logs output summary.
[password_test]    Allows configuration of a hashed password.
      Will redact the user's password in the logs output summary.
    Allows preventing the startup of the sshd bootstrap.
    Allows preventing the startup of the sshd daemon.
  Customised SFTP configuration
    Allows configuration of the user's ChrootDirectory where %u is replaced with the username in the path.
      Displays the chroot path in the logs output summary.
      Configures the user with the /sbin/nologin shell.
        Displays the user's shell in the logs output summary.
      Allows the user to write to their HOME directory.
    Allows configuration of SFTP access to a volume mounted from another container.
37 examples, 0 failures
0m0.033s 0m0.032s
0m1.399s 0m0.830s
```

**Comment by rylnd** [comment]
@jdeathe I noticed something similar on Travis; I think it has to do with the CI service streaming the build's output vs `shpec` rewriting output, but that's just a guess.

@Alexandre-Silva any thoughts here? Is this an artifact of the streaming output, or is this a legitimate problem with #100's implementation?

**Comment by rylnd** [comment]
@jdeathe one more clarification: is this causing issues for your test suite (e.g. making assertions against the output), or is this mainly a cosmetic issue?

**Comment by jdeathe** [comment]
@rylnd That's true; It's not causing me any issues other than cosmetic. I haven't upgraded my local version yet to test your theory of this occurring on CI servers. For reference the CI service I am using is running on the following: Kernel: Linux 3.13.0-32-generic Ubuntu 14.04.1 LTS

**Comment by rylnd** [comment]
@jdeathe yeah, you can observe the same thing on our Travis builds: https://travis-ci.org/rylnd/shpec/jobs/226266278.

@Alexandre-Silva what do you think? Is there a way to accomplish this feature without rewriting output?

**Comment by jdeathe** [comment]
@rylnd - Looking at the test cases for #100 I now understand that this feature is intended to indicate when an it/end block contains multiple asserts. 

In my affected test cases I don't have multiple asserts in a single block but instead I am nesting cases. I think nesting cases solves the same issue and more clearly indicates the reason for each assert e.g. https://github.com/jdeathe/centos-ssh/blob/2.2.1/test/shpec/operation_shpec.sh#L83-L96. As such, I don't really benefit from the `(x2)` addition but can live with it now I understand why it's being added.

**Comment by Alexandre-Silva** [comment]
@rylnd Refactoring this feature to avoid rewriting ouput should be possible. It would mean changing shpec to printf the assert message at the end of each block rather than on each assert. However, refactoring of shpec's core assert logic would be needed to accomplish this task. The current solution was chosen because it was relatively simple to implemente and thus had the least risk of breaking things.

**Comment by rylnd** [comment]
> refactoring of shpec's core assert logic would be needed to accomplish this task

Yeah, that's kinda what I figured. So, this isn't a fatal bug (shpec is not (yet) following any standards regarding output, and I would definitely not recommend relying upon it), but I agree that it's a bummer. For now, I'm probably going to file this under "things shpec can't do because it's not robust enough."

@jdeathe your nesting case is interesting. I'd not intended shpec to be used that way, and I doubt the output was pretty _before_ #100, but it's nice to know that such a thing is possible. If you have any particularly neat examples, I would love to see them added to [the wiki].

**Comment by jdeathe** [comment]
Hi @rylnd - The output looked fine before; I have provided an example in the initial report above. I didn't realise I was doing anything special with the test cases I just found I had quite a lot so wanted to show a grouping of related tests after setting up a state. I guess I could break the tests down into more describe blocks instead; I'll have a think about it.

**Comment by rylnd** [comment]
@jdeathe sounds good! Thanks for your interest and support.
