### ISSUE TITLE
Installation from raw.github.com fails

### ISSUE THREAD

**Issue by jdeathe** [rylnd/shpec#124]
Following the install instructions in the readme currently fails due to a 503 response from: https://raw.github.com/rylnd/shpec/master/install.sh

To reproduce issue:
```
bash -c "$(curl -LSs https://raw.github.com/rylnd/shpec/master/install.sh)"
```
Response:
```
bash: -c: line 1: syntax error near unexpected token `newline'
bash: -c: line 1: `<?xml version="1.0" encoding="utf-8"?>'
```

Work-around install using:
```
bash -c "$(curl -LSs https://raw.githubusercontent.com/rylnd/shpec/master/install.sh)"
```

**Comment by rylnd** [comment]
@jdeathe Thanks for noticing this! It looks like that subdomain has been deprecated. PR is most welcome, otherwise I'll update this when I can.

**Comment by jdeathe** [comment]
Hi @rylnd, I've submitted https://github.com/rylnd/shpec/pull/125 for your consideration.
