### ISSUE TITLE
equal matcher should handle \n

### ISSUE THREAD

**Issue by bendycode** [rylnd/shpec#23]
This fails:

``` bash
describe "equal"
  it 'handles \n character'
    string_with_new_line="x\ny"
    output='x
y'
    assert equal "$string_with_new_line" "$output"
end_describe
```

**Comment by hlangeveld** [comment]
According to the opengroup (POSIX) definition, the string "x\ny" should be four characters long, and not contain a newline character.  This assertion should fail.
