### ISSUE TITLE
Add shpec to bpkg

### ISSUE THREAD

**Issue by rylnd** [rylnd/shpec#54]
Related to #8, [bpkg](https://github.com/bpkg/bpkg) looks to be a nice little package manager that I'd like to get on.

We just need to ensure shpec conforms to [their guidelines](https://github.com/bpkg/bpkg#packaging-best-practices).

**Comment by AdrieanKhisbe** [comment]
Will do, I was look for bash antigen the other days, but was not as lucky as you :)

**Comment by rylnd** [comment]
Closed with the completion of #83,  https://github.com/bpkg/bpkg.github.io/pull/19 and [adding it to bpkg's index](https://github.com/bpkg/bpkg/wiki/index/a42263f748899827a4f31ef825390977b6eba0f90
