### ISSUE TITLE
Run CI against multiple shells

### ISSUE THREAD

**Issue by rylnd** [rylnd/shpec#61]
This was added in #59 and revised in hlangeveld/shpec#1. Which shells should be run/supported?

**Comment by AdrieanKhisbe** [comment]
- bash (of course)
- dash 
- zsh (with disabling end)
- ksh

**Comment by AdrieanKhisbe** [comment]
I consider *fish* is to different to be suported. (syntax)

**Comment by rylnd** [comment]
How about plain old `sh`?

**Comment by AdrieanKhisbe** [comment]
`s what` ? :)

**Comment by AdrieanKhisbe** [comment]
we could try :).

in case we are lucky enough to discover we didn't used too advanced feature :)

**Comment by rylnd** [comment]
I think the four that we have running up on travis (bash, dash, ksh, zsh) are good for now. We should open a separate issue for fixing zsh.

**Comment by locochris** [comment]
@rylnd - actually `sh` works fine - so you might as well add it #73

**Comment by hlangeveld** [comment]
These days, there is no more plain old `sh`.  On ubuntu it's unadorned `dash`, on others, its linked to bash, which will restrict itself.

On Solaris 8 and 10 `/bin/sh` was an actual non-POSIX Bourne shell, with `/usr/xpg3/bin/sh` (or was it xpg4)  a slightly modified `ksh88`.  In OpenSolaris, it got replaced with `ksh93`. 

I do know that just specifying plain `sh` is going to give non-reproducable results.
