### ISSUE TITLE
Updating milestone

### ISSUE THREAD

**Issue by AdrieanKhisbe** [rylnd/shpec#64]
two month ago I created a 0.2 milestone to introduce the new language feature I was forwking on.

With latest developpement and awesome work of @hlangeveld and https://github.com/rylnd/shpec/pull/58 PR I think it might be better to update this and make:

- 0.2 milestone : *posix and ci integration*
- 0.3 milestone : *new language features*

What do you think about this?

**Comment by rylnd** [comment]
@AdrieanKhisbe that seems fine. Anything pre-1.0 is pretty much a free-for-all in terms of versioning, so we've been doing it ad hoc so far.

Note that the milestones don't have to correspond to version numbers, either. For example, we could simply have a "posix" milestone.

**Comment by AdrieanKhisbe** [comment]
I made one for the posix since we introduce the shpec function. deserve a bump for me :)

**Comment by rylnd** [comment]
@AdrieanKhisbe Is this resolved? I don't see a POSIX milestone anywhere, but we're now past it, anyway.

**Comment by AdrieanKhisbe** [comment]
had forgot to complete it. now done.
