### ISSUE TITLE
Need a namespace convention for internal variables in bin/shpec

### ISSUE THREAD

**Issue by hlangeveld** [rylnd/shpec#70]
As mentioned in #65, I renamed the variable `$file` into `$_shpec_file` in the main shpec function/script.

The idea being, that by reserving a namespace for internal variables, any code under test can use any variable name as long as it does not clash with the shpec internal namespace.

Suggestions:

  * `_shpec_*`  or `_sh_*`

Changing all internal variables is straightforward work, and I'm willing to put that time in.

**Comment by AdrieanKhisbe** [comment]
I feel that `_sh_*` might be confusing even if it has the advantage to be shorter. 

Otherwise that's a welcome improvement :)

**Comment by rylnd** [comment]
I like `_shpec_*`. :+1:  for clarity over brevity.
