### ISSUE TITLE
Package Managers

### ISSUE THREAD

**Issue by rylnd** [rylnd/shpec#8]
Homebrew, RPM, etc. We've got a Makefile, let's use it.

I've got [this formula](https://gist.github.com/rylnd/4704461) that needs to be updated to use the Makefile, and it sounds like @locochris is working on an RPM script.

**Comment by AdrieanKhisbe** [comment]
This is a suggestion, for zsh teminal [antigen](https://github.com/zsh-users/antigen) could be used to install `shpec`from the github repositery.

(there would be no need of install script and Makefile)

**Comment by rylnd** [comment]
@AdrieanKhisbe while I wouldn't want to make users dependent upon antigen for installation, adding antigen compatibility sounds like a great idea!

I'm not sure exactly what that entails at the moment, but I'll look into it.

If you're feeling up to it, please feel free to submit a PR.

**Comment by AdrieanKhisbe** [comment]
Hey @rylnd, sorry for the late answer, I just got released for a semester end blackhole. ^^

The point as exactly to make it installable via antigen without introducing a dependance, 
I'm gonna fork a try to do it :)

**Comment by AdrieanKhisbe** [comment]
Hey Hey, I made the antigen plugin compatible install: https://github.com/rylnd/shpec/pull/48

To do this I created a `shpec.plugin.zsh`, file which is source by antigen when loading the plugin.
I made the file define a shpec alias pointing to where the shpec script is. (antigen clone the repo
in some `.antigen/repo` folder with a name matching repo)

If you use zsh and antigen and want to try it, add `antigen bundle AdrieanKhisbe/shpec` in your `zshrc`. (waiting the merge is realised)

If you consider we should bump to 0.1.2, tell me, I will do it before you merge the request.

Best regards

**Comment by AdrieanKhisbe** [comment]
Hey @rylnd,  should we close the issue, or see if we can publish it through `pip`or `npm`?

**Comment by rylnd** [comment]
I'm fine doing those as people request them.

@mathias was referred me to https://github.com/bpkg/bpkg, I've been meaning to send them a PR but I wanted to ensure we met the guidelines first. I'm fine with closing this and opening an issue specifically for that, though.

**Comment by rylnd** [comment]
Closed by #48
