### ISSUE TITLE
Update screenshot in README

### ISSUE THREAD

**Issue by rylnd** [rylnd/shpec#80]
Lots of retina displays floating around the internet these days, and we've also got some new timing output. Time for a new screenshot!

**Comment by rylnd** [comment]
This should be done now. The screenshot lives in the wiki repo, which I updated. I guess manual commits to the wiki don't show up in the wiki's "revisions," which is a bummer. Rest assured, though, the change was actually made. :wink:

**Comment by locochris** [comment]
hmmm yer - @rylnd / anyone? know how to access the hidden world of the github repo for `repo.wiki`?
The best I could find was:
  https://github.com/rylnd/shpec/wiki/_history
.. but its still doesn't show much.

**Comment by rylnd** [comment]
Yep, that's it! That's the entire history; we haven't done much in the wiki.

**Comment by locochris** [comment]
I can't figure out the url of an actual commit - eg. to see which files got changed.
(there's no links in that https://github.com/rylnd/shpec/wiki/_history)

**Comment by rylnd** [comment]
Yeah, I tinkered with the web interface, and it looks like you can choose to view a diff between two SHAs by clicking the checkboxes next to those two changes and selecting 'Compare Revisions.' The resulting URL seems to be of the form https://github.com/rylnd/shpec/wiki/_compare/sha1...sha2. In this case, it'd be [this guy](https://github.com/rylnd/shpec/wiki/_compare/cf64c7e61cef8b5c554557fb479edc9e3fa2ef56...fe68025379486e2cc034d7bf30c4a753536a27bf)

The diff is a lot more rudimentary than their normal interface, though (e.g. they don't have image diffs). I've generally just found it easier to clone the wiki repo and treat it like any other repo.
