### ISSUE TITLE
provide a real regex matcher

### ISSUE THREAD

**Issue by schorsch3000** [rylnd/shpec#96]
The matchers `match` and `no_match` should, as documented, provide regex-functionality.
In fact they "only" provide glob-like wildcard functionality.

This issue doubles as a bug-report and as a feature request.

The bug-report addresses the documentation, as i think the given functionality is as intended, but the wording in the `README.md` is wrong.

The feature-request addresses the lack of said regex-functionality.
It would be really neat to have a matcher that matches using regex, maybe provided by (e)grep.

I'll happily provide that functionality via pullrequest, but i'm lost at naming those both matchers, the positive and negative one, since the best names are used.

Should we use grep / egrep and no_grep / no_egrep?

**Comment by rylnd** [comment]
@schorsch3000 If the implementation with `grep` is backwards-compatible with the existing implementation of `match`, I see no reason why it cannot just be replaced.
